### PR TITLE
docs(utils): remove back space(%08) in isDifferentArray.spec.ts file name

### PR DESCRIPTION
**Pull request by ChanhyukPark-Tech**
## Overview

image

file name is changed without any change

image

there are two docs `isDifferentArray`

When I looked it up, there was a backspace(%08) hidden in front of the word spec in the file name.

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

### CODE REVIEW

**Comment by ChanhyukPark-Tech** [comment]
I think `isDifferentArray` function should be located inside of array folder 

`AS-IS` : utils/src/isDifferentArray
`TO-BE` : utils/src/array/isDifferentArray

This is because it is a function related to an array.

**Review by raon0211 — APPROVED** [review]
That was a catch. Thanks!

**Comment by raon0211** [comment]
>I think isDifferentArray function should be located inside of array folder
>
>AS-IS : utils/src/isDifferentArray
>TO-BE : utils/src/array/isDifferentArray
>
>This is because it is a function related to an array.

I agree, can you make this a different pull request for this?

**Comment by ChanhyukPark-Tech** [comment]
yes! I will make other PR thanks

**Pull request merged**
