### PR TITLE
test(utils): Add test code for generateID

### PR DESCRIPTION
**Pull request by ChanhyukPark-Tech**
## Overview

I wrote test code for generateID which belong to @toss/utils To ensure stability, I have written a test code

`nextUniqueId` which is local variable in generateID should be initialized to 0 for every test case
so I used jest.resetModules 
resetModules help our individual test code run independently from other test cases

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed. => I made test case !

### CODE REVIEW

**Comment by raon0211** [comment]
I believe test codes should clearly show the author's intended behavior for that function.

I think what we actually intend for `generateID` is to return different `string` values each time it is called. Whether or not the ID is incremented is implementation detail. In this manner, what about changing the test code as the following code?

```typescript
it('returns different string values each time it is called', () => {
  const id1 = generateID();
  const id2 = generateID();
  const id3 = generateID();

  expect(id1).not.toEqual(id2);
  expect(id1).not.toEqual(id3);
  expect(id2).not.toEqual(id3);
});

it('should start with the prefix, if given', () => {
  const id = generateID('toss');

  expect(id.startsWith('toss')).toBe(true);
});
```

**Comment by raon0211** [comment]
By writing the test code as above, the test code will become more concise and easier to read.

**Comment by ChanhyukPark-Tech** [comment]
Thank you for explaining such a good example and the purpose of the test code.
I've always thought a lot about what criteria to write the test code, but you(raonraon0211) told me that the test code should be able to test the behavior that the author intended. Just by looking at the test code you wrote as an example, I understood the intention right away. 
I'll fix it and push it to this branch! Thank you.💪

**Review by raon0211 — APPROVED** [review]
LGTM :+1:

**Comment by ChanhyukPark-Tech** [comment]
thx for solving install error!

**Comment by ChanhyukPark-Tech** [comment]
The method you recommended is written in English. The other test codes were explained in Korean, so which one should I write in English or Korean?!

**Comment by raon0211** [comment]
We are planning to migrate our repository into English 😓

**Pull request merged**
