### PR TITLE
fix(@toss/utils): correct hex validation to prevent unexpected color parsing

### PR DESCRIPTION
**Pull request by BO-LIKE-CHICKEN**
## Overview

While working on a project that exclusively uses Hex color codes, I discovered that converting existing library variables to RGBA format does not properly handle formats like #FFFFFF80. Upon further inspection of the library, I identified several issues.

1.  The library determines the color format based on the string's length, allowing for errors like `e3e3e33` (an accidental extra '3') to pass through tests. This could potentially lead to unintended side effects, such as:

    - TypeScript does not flag this as an error, resulting in oversight that remains unnoticed until runtime.
    - The user expects the color rgba(227,227,227,1) but gets an unexpected rgba(62,62,51,1) due to the typo. To prevent this, I've:
        1. Added test cases.
        2. Implemented an alternative conditional approach (starting with “#”) to pass these tests. Although there are concerns about backward compatibility, this seems to be the most reliable solution.
2. The library does not support Hex Colors with alpha values, like #FFFFFF80. This issue was not addressed in the pull request, as it seems to require a policy decision on handling alpha values in Hex colors.
3. The library does not support shorthand Hex Colors like #FFF. Although the existing test cases already throw errors for this format, I've only added more test cases to cover these scenarios. 

Issue 1 clearly presents a problem, while the approach to addressing issues 2 and 3 is left to your discretion.

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

### CODE REVIEW

**Comment by ssi02014** [comment]
Looks like an interesting Pull Request. I have a minor comment to make! 🙏
I think I can shorten the 2 validations by utilizing regular expressions.
In my opinion, it becomes simpler and more readable..! 
What do you think? 🤗

The code below passes both the existing and added test code!! 💪

(+) Additionally, slash should be written in English, and I understand that existing code written in Korean is being changed incrementally

```diff
+ export function isValidHexValue(hex: string) {
+  const regex = /^#?[0-9A-Fa-f]{6}$/;
+  return regex.test(hex);
+ }

export function hexToRgba(hex: string, alpha = 1) {
+  if (!isValidHexValue(hex)) {
+    throw new Error(`Invalid hex value: ${hex}`);
+  }

  if (!isAlphaValue(alpha)) {
    throw new Error(`Invalid alpha value(0~1): ${alpha}`);
  }

  const normalizedHex = hex.startsWith('#') ? hex.slice(1) : hex;

- if (normalizedHex.length !== 6) {
-   throw new Error(`잘못된 normalizedHex 값의 길이입니다. 정확히 6자리여야 합니다: ${normalizedHex}`);
- }

  const r = parseHexValueStr(normalizedHex.slice(0, 2));
  const g = parseHexValueStr(normalizedHex.slice(2, 4));
  const b = parseHexValueStr(normalizedHex.slice(4, 6));

-  if ([r, g, b].some(value => Number.isNaN(value) || !isRGBDecimalValue(value))) {
-    throw new Error(`잘못된 hex값 입니다: ${hex}`);
-  }

  return `rgba(${r},${g},${b},${alpha})`;
}
```

**Comment by BO-LIKE-CHICKEN** [comment]
> @BO-LIKE-CHICKEN Hi! 👋 Looks like an interesting Pull Request. I have a minor comment to make! 🙏 I think I can shorten the 2 validations by utilizing `regular expressions`.
> 
> In my opinion, it becomes simpler and more readable..! What do you think? 🤗
> 
> The code below passes both the existing and added test code!! 💪
> 
> (+) Additionally, slash should be written in `English`, and I understand that existing code written in Korean is being changed incrementally
> 
> ```diff
> + export function isValidHexValue(hex: string) {
> +  const regex = /^#?[0-9A-Fa-f]{6}$/;
> +  return regex.test(hex);
> + }
> 
> export function hexToRgba(hex: string, alpha = 1) {
> +  if (!isValidHexValue(hex)) {
> +    throw new Error(`Invalid hex value: ${hex}`);
> +  }
> 
>   if (!isAlphaValue(alpha)) {
>     throw new Error(`Invalid alpha value(0~1): ${alpha}`);
>   }
> 
>   const normalizedHex = hex.startsWith('#') ? hex.slice(1) : hex;
> 
> - if (normalizedHex.length !== 6) {
> -   throw new Error(`잘못된 normalizedHex 값의 길이입니다. 정확히 6자리여야 합니다: ${normalizedHex}`);
> - }
> 
>   const r = parseHexValueStr(normalizedHex.slice(0, 2));
>   const g = parseHexValueStr(normalizedHex.slice(2, 4));
>   const b = parseHexValueStr(normalizedHex.slice(4, 6));
> 
> -  if ([r, g, b].some(value => Number.isNaN(value) || !isRGBDecimalValue(value))) {
> -    throw new Error(`잘못된 hex값 입니다: ${hex}`);
> -  }
> 
>   return `rgba(${r},${g},${b},${alpha})`;
> }
> ```

@ssi02014 Hello! First, the content you've suggested looks entirely valid :) Initially, we added features trying not to significantly alter the existing codebase structure. However, if it's possible to make changes for better functionality, it seems appropriate to modify it as you suggested. Additionally, thank you for letting us know that we are gradually changing from using Korean in slashes to English, and that we are incrementally changing existing code written in Korean!

Therefore, as you suggested, we have modified the code and further enhanced it by:
- Removing the remaining Korean from the test code.
- Writing tests for a broader range of edge cases.

These changes will enhance the readability of the code and make it easier for developers to understand by clearly defining the cases we support. Thank you for your suggestion!

**Comment by ssi02014** [comment]
@BO-LIKE-CHICKEN 
Cool! It looks much better to me! 🚀 
But in the end, it needs a review by a maintainer

**Review by raon0211 — APPROVED** [review]
This seems more accurate. Thanks!

**Comment by ssi02014** [comment]
@BO-LIKE-CHICKEN Cool!

**Pull request merged**
