### PR TITLE
fix(error-boundary): connect ref

### PR DESCRIPTION
**Pull request by manudeli**
## Overview
Connect ref correctly, what I didn't connect before, BaseErrorBoundary with ErrorBoundary

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

### CODE REVIEW

**Review by raon0211 — APPROVED** [review]

**Comment by raon0211** [comment]
Can you also add tests to make sure refs are working?

**Comment by manudeli** [comment]
@raon0211 I added it.

**Comment by manudeli** [comment]
> Can you also add tests to make sure refs are working?

@raon0211 I added it.

**Comment by manudeli** [comment]
@raon0211 when I was adding test codes, I found wrong type, so I fixed it in 8ce075d

**Review by raon0211 — APPROVED** [review]
Thanks!

**Pull request merged**
