### PR TITLE
refactor(@toss/emotion-utils): SpacingProps: Replace `never` with `Omit` for children

### PR DESCRIPTION
**Pull request by SEOKKAMONI**
## Overview
SpacingProps: Replace `never` with `Omit` for children

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

### CODE REVIEW

**Comment by okinawaa** [comment]
I want to know what effect this PR has 😊

**Comment by SEOKKAMONI** [comment]
> I want to know what effect this PR has 😊

I should have written the explanation when I posted the PR. I'm sorry 

There are many reasons, but the most compelling one is that unnecessary automatic completion of "children" in props can create confusion for developers.

image

**Comment by ssi02014** [comment]
I saw this pull request and was intrigued, so here's a small comment...! 🙏

```ts
type SpacingProps = Omit<React.HTMLProps<HTMLDivElement>, "size" | "children" | "direction"> & {
    children?: undefined;
    direction?: AxisDirection | undefined;
    size: CSSPixelValue;
}
```
The `SpacingProps` type has `children?: undefined` as shown above. 

```tsx
<Spacing direction="horizontal" size={40} />
```
Given the use case of Space, I don't think `children?: undefined` is a necessary type.
I agree with @SEOKKAMONI  that it's appropriate to exclude the `children` type.

**Comment by SEOKKAMONI** [comment]
> I saw this pull request and was intrigued, so here's a small comment...! 🙏
> 
> ```ts
> type SpacingProps = Omit<React.HTMLProps<HTMLDivElement>, "size" | "children" | "direction"> & {
>     children?: undefined;
>     direction?: AxisDirection | undefined;
>     size: CSSPixelValue;
> }
> ```
> 
> The `SpacingProps` type has `children?: undefined` as shown above.
> 
> ```tsx
> <Spacing direction="horizontal" size={40} />
> ```
> 
> Given the use case of `Spacing`, I think it's appropriate to exclude the `children` type, the same as @SEOKKAMONI

I'm curious about why the type is explicitly set to 'undefined' for 'children' when it's not necessary. I think this change actually lowers the DX by providing unnecessary autocompletion to developers. 

and I'm also curious why size and direction are being excluded using Omit instead of ExtendHTMLProps.

I think I might be wrong understandIf I gave me wrong understanding understandingstanding, please tell me when I got wrong understand

Lastly, thank you for always provoking my curiosity! Your comments are a great help to my learning!!

**Comment by ssi02014** [comment]
@SEOKKAMONI 👋
It seems like my intention wasn't properly conveyed! 😭
```tsx
type SpacingProps = ExtendHTMLProps<
  HTMLDivElement,
  {
    children?: never;
    direction?: AxisDirection;
    size: CSSPixelValue;
  }
>;
```
The type of the existing `SpacingProps` ultimately ends up being as follows!
```tsx
type SpacingProps = Omit<React.HTMLProps<HTMLDivElement>, "size" | "children" | "direction"> & {
    children?: undefined;
    direction?: AxisDirection | undefined;
    size: CSSPixelValue;
}
```

스크린샷 2024-02-11 오전 3 19 09

You can understand this by looking at the code where `ExtendHTMLProps` is defined...!
```tsx
export type ExtendHTMLProps<Elem extends HTMLElement, T> = Omit<HTMLProps<Elem>, keyof T> & T;
```
The key point is that I also agree with your opinion!! 🤗

**Review by raon0211 — APPROVED** [review]
Thanks!

**Pull request merged**
