### PR TITLE
docs(framer-motion): support i18n and add code blocks

### PR DESCRIPTION
**Pull request by pongdang**
## Overview

Hi 😃

I wanna suggest that live editor(code blocks) in docusaurus.

- Adds korean and english documentations for `@toss/framer-motion`.
- Adds [Code Blocks](https://docusaurus.io/docs/markdown-features/code-blocks) about `@toss/framer-motion` example.

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

### CODE REVIEW

**Review by HoseungJang — COMMENTED** [review]
Thanks a lot for your contribution.

But I think we don't have to support live editor for @toss/framer-motion because It's simply wrapper of framer-motion and has completely same interface.

It's enough that we add link to documentation of [framer-motion](https://www.framer.com/motion/).

**Comment by pongdang** [comment]
Thanks for reply, @HoseungJang 🙇‍♀️

That's so reasonable thinking, I agree!

I'll remove live editor in this PR.

**Review by raon0211 — APPROVED** [review]
Thanks for your contribution, @pongdang !

**Comment by raon0211** [comment]
We plan to add live code blocks to our website, and this pull request will help us a lot. Meanwhile, what about adding live code blocks in other libraries like @toss/utils or @toss/impression-area?

**Comment by raon0211** [comment]
I agree that live code blocks don’t help much in @toss/framer-motion.

**Comment by pongdang** [comment]
@raon0211
Oh thanks for consent to my suggestion! 🤸‍♀️

I'll comeback with other PR 🙇‍♀️

**Pull request merged**
