### PR TITLE
fix(@toss/react): improve readability and add dependencies `useOutsideClickEffect`

### LINKED ISSUE #449: [Question]:useOutsideClickEffect dependancies
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: packages/react/react/src/hooks/useOutsideClickEffect.ts

### **Overview**

when useOutsideClickEffect, it will rerender everytime.
there is no dependacies on useOutsideClickEffect hook

### **Describe the solution you'd like**

when i use useOutsideClickEffect Hook, it should add eventListner once. and should remove it when component unmont.
i think 
```
  useEffect(() => {
    document.addEventListener('click', handleDocumentClick);
    document.addEventListener('touchstart', handleDocumentClick);

    return () => {
      document.removeEventListener('click', handleDocumentClick);
      document.removeEventListener('touchstart', handleDocumentClick);
    };
  });
```
to
```

  useEffect(() => {
    document.addEventListener('click', handleDocumentClick);
    document.addEventListener('touchstart', handleDocumentClick);

    return () => {
      document.removeEventListener('click', handleDocumentClick);
      document.removeEventListener('touchstart', handleDocumentClick);
    };
  }, []);
```
is there any reason there are no dependancies on this hook? 
im curious about it

### PR DESCRIPTION
**Pull request by Collection50**
### AS-IS

```jsx
useEffect(() => {
  containers.current = (Array.isArray(container) ? container : [container]).filter(isNotNil);
}, [container]);
```

```jsx
useEffect(() => {
  document.addEventListener('click', handleDocumentClick);
  document.addEventListener('touchstart', handleDocumentClick);

  return () => {
    document.removeEventListener('click', handleDocumentClick);
    document.removeEventListener('touchstart', handleDocumentClick);
  };
}, []);
```

<br/>

### TO-BE

```jsx
useEffect(() => {
  containers.current = [container].flat(1).filter(isNotNil);
}, [container]);
```

```jsx
useEffect(() => {
  document.addEventListener('click', handleDocumentClick);
  document.addEventListener('touchstart', handleDocumentClick);

  return () => {
    document.removeEventListener('click', handleDocumentClick);
    document.removeEventListener('touchstart', handleDocumentClick);
  };
}, [handleDocumentClick]);
```

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

close #449

### CODE REVIEW

**Comment by okinawaa** [comment]
The flat method was introduced in ES2019 (ES10). Therefore, this code will work well in modern browsers, but it might not be supported in older browsers. Is this acceptable?

**Comment by Collection50** [comment]
> The flat method was introduced in ES2019 (ES10). Therefore, this code will work well in modern browsers, but it might not be supported in older browsers. Is this acceptable?

The part I was looking for was the [flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) !

I'd appreciate it if you could tell me how to know the current status of support for the older browser you mentioned!

**Review by okinawaa — APPROVED** [review]
We don't have a specific browser range! yet 
According to the link you sent me, it says it complies with the `baseline`.
I think that's enough!

**Comment by Collection50** [comment]
> We don't have a specific browser range! yet According to the link you sent me, it says it complies with the `baseline`. I think that's enough!

Thank you!!

**Pull request merged**
