### PR TITLE
fix(use-query-param): do narrow type of useNextRouter

### PR DESCRIPTION
**Pull request by manudeli**
## do narrow type of useNextRouter
If using suspense, useNextRouter().isReady don't need to be boolean. so I corrected it and add test code.

### referenece
image

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

### CODE REVIEW

**Review by HoseungJang — COMMENTED** [review]
I think this is too complicated. Because a person who set `suspense` to true basically doesn't have to check what the value `router.isReady` has.

**Comment by manudeli** [comment]
> I think this is too complicated. Because if you set `suspense` to `true`, basically you don't have to check what the value `router.isReady` has.

@HoseungJang 
I think this Pull Request is meaningful because, like you said, router.isReady doesn't have to be checked. "Only if suspense: true". but how about, suspense: false or boolean?

1. Before this Pull Request, isReady came out as a boolean, so it may be confusing for users, but after this change, it is clear isReady: true.
2. if want to use useNextRouter as suspense: boolean, isReady must be boolean because we can't know whether to execute throw waitForRouterReady().
3. if want to use useNextRouter as suspense: false, isReady must be boolean because you can't execute throw waitForRouterReady().

It's not more complicated, I think it's more simpler. If you still think it's complicated, What's complicated? Some more explanation is needed.

**Comment by HoseungJang** [comment]
> Before this Pull Request, isReady came out as a boolean, so it may be confusing for users, but after this change, it is clear isReady: true.

I think there isn't any confusing if users understand [how router.isReady will be changed.](https://nextjs.org/docs/pages/building-your-application/rendering/automatic-static-optimization)

> if want to use useNextRouter as suspense: boolean, isReady must be boolean because we can't know whether to execute throw waitForRouterReady().

I think it's helpful for you to see how suspense works.

And, to say once again, basically you don't have to check isReady when you set suspense to true, then how can this change be more simpler?

**Comment by HoseungJang** [comment]
To be more clear, there are two use cases, checking `if (router.isReady)` or not.

Then, for the former case, is it meaningful to check the boolean value always evaluated as true?

**Pull request closed without merging**
